- containers/images/angular/Dockerfile
It's minimal change - fixed from #3 where I forget to add this.
> Add EXPOSE 3000 to angular Dockerfile

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/debian-12-slim/.gitignore
- containers/images/debian-12-slim/Dockerfile
- containers/images/debian-12-slim/README.md
- containers/images/debian-12-slim/init.sh
Add the debian 12 slim build automation
Internal task
> Debian 12 slim

- containers/build-container.sh
- containers/docker-build-order.py
- containers/images/golang-1.23/Dockerfile
- containers/images/golang-1.23/README.md
- containers/images/golang-1.23/init.sh
- containers/images/golang-1.24/Dockerfile
- containers/images/golang-1.24/README.md
- containers/images/golang-1.24/init.sh
- containers/images/kong/init.sh
- containers/images/python-3.11/Dockerfile
- containers/images/python-3.11/README.md
- containers/images/python-3.11/init.sh
- containers/images/python-3.12/Dockerfile
- containers/images/python-3.12/README.md
- containers/images/python-3.12/init.sh
- containers/images/python-3.13/Dockerfile
- containers/images/python-3.13/README.md
- containers/images/python-3.13/init.sh
- containers/images/python/README.md
- containers/tests/test_golang.py
Add new runtimes part 1:
1. Python 3.13
2. Python 3.12
3. Python 3.11
4. Golang 1.24
5. GoLang 1.23
Internal task
> Experimental runtime work

- .github/workflows/build-manual.yml
- containers/images/debian-11-slim/.gitignore
- containers/images/debian-11-slim/Dockerfile
- containers/images/debian-11-slim/README.md
- containers/images/debian-11-slim/init.sh
Add debian-11-slim as requested by the client.
Internal task
This is an external public repository; for the sake of transparency, please use English in the review.
> Add debian-11-slim

- containers/images/activemq/init.sh
- containers/images/camel-k/Dockerfile
- containers/images/camel-k/README.md
- containers/images/camel-k/init.sh
Update the activemq so it's automatically updated :).
- Move camel-k to the Debian instead of Rocky 9
- Internal task
> Auto update containers

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/gcc-13/Dockerfile
- containers/images/gcc-13/README.md
- containers/images/gcc-13/init.sh
- containers/images/gcc-14/Dockerfile
- containers/images/gcc-14/README.md
- containers/images/gcc-14/init.sh
- containers/images/gcc-15/Dockerfile
- containers/images/gcc-15/README.md
- containers/images/gcc-15/init.sh
- containers/tests/test_gcc-13.py
- containers/tests/test_gcc-14.py
- containers/tests/test_gcc-15.py
This PR adds new gcc-13, gcc-14, gcc-15 container images.
- Internal task
> Add gcc 13, gcc 14, gcc 15 (snapshot)

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/rabbitmq-4/10-defaults.conf
- containers/images/rabbitmq-4/20-management_agent.disable_metrics_collector.conf
- containers/images/rabbitmq-4/Dockerfile
- containers/images/rabbitmq-4/README.md
- containers/images/rabbitmq-4/docker-entrypoint.sh
- containers/images/rabbitmq-4/init.sh
- containers/tests/test_rabbitmq-4.py
- containers/tests/test_rabbitmq.py
Add RabbitMQ v4 on debian-12-slim for ezdrp
Internal task
This is an external public repository; for the sake of transparency, please use English in the review.
> Add RabbitMQ v4 container image

- containers/images/cnpg-16-oneshot/Dockerfile.disabled
- containers/images/cnpg-16/Dockerfile
- containers/images/cnpg-17/Dockerfile
- containers/tests/test_cnpg-16.py
- containers/tests/test_cnpg-17.py
The uncommented locale in /etc/locale.gen is enough for CNPG
Internal task
> Update the cnpg so PL lang is optional

- containers/images/cnpg-16/README.md
- containers/images/cnpg-17/README.md
The pl_PL.UTF-8 is no longer default locale :). Add info about changing locale.
Internal task
> Micro cnpg readme change

- .github/workflows/build-manual.yml
> add redis-exporter to build-manual.yaml

- .github/workflows/build-manual.yml
- containers/images/gcc-13/Dockerfile
- containers/images/gcc-14/Dockerfile
- containers/images/gcc-15/Dockerfile
- containers/images/gcc-15/README.md
- containers/images/gcc-15/init.sh
- containers/images/gcc-16/Dockerfile
- containers/images/gcc-16/README.md
- containers/images/gcc-16/init.sh
- containers/tests/test_gcc-16.py
> Gcc 15 release update

- containers/images/redis-operator/.gitignore
- containers/images/redis-operator/Dockerfile
- containers/images/redis-operator/README.md
- containers/images/redis-operator/conf.sh
- containers/images/redis-operator/init.sh
> add redis-operator

- .github/workflows/build-manual.yml
> add redis-operator to build-manual.yaml

- containers/images/redis-sentinel/Dockerfile
- containers/images/redis-sentinel/README.md
- containers/images/redis-sentinel/entrypoint.sh
- containers/images/redis-sentinel/healthcheck.sh
- containers/images/redis-sentinel/init.sh
- containers/images/redis-sentinel/sentinel.conf
> Rk redis sentinel

- .github/workflows/build-manual.yml
> add redis-sentinel to build-manual.yaml

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/nginx-mainline-otel/Dockerfile
- containers/images/nginx-mainline-otel/README.md
- containers/images/nginx-mainline-otel/conf.sh
- containers/images/nginx-mainline-otel/init.sh
- containers/images/nginx-mainline-otel/prepare-container-to-get-version.sh
- containers/images/nginx-mainline-perl/Dockerfile
- containers/images/nginx-mainline-perl/README.md
- containers/images/nginx-mainline-perl/conf.sh
- containers/images/nginx-mainline-perl/init.sh
- containers/images/nginx-mainline-perl/prepare-container-to-get-version.sh
- containers/images/nginx-mainline/.gitignore
- containers/images/nginx-mainline/Dockerfile
- containers/images/nginx-mainline/README.md
- containers/images/nginx-mainline/init.sh
- containers/images/nginx-mainline/prepare-container-to-get-version.sh
- containers/images/nginx-stable-otel/init.sh
- containers/images/nginx-stable-perl/init.sh
- containers/images/nginx-stable/init.sh
- containers/tests/test_nginx-mainline-otel.py
- containers/tests/test_nginx-mainline-perl.py
- containers/tests/test_nginx-mainline.py
Add Nginx mainline container files, add iproute package (`ss` command).
Internal task
> Nginx mainline

- .github/workflows/build-manual.yml
- containers/images/jre-21/Dockerfile
- containers/images/jre-21/README.md
- containers/images/jre-21/docker-entrypoint.sh
- containers/images/jre-21/entrypoint.sh
- containers/images/jre-21/init.sh
- containers/tests/test_jre-21.py
Adds Temurin compiled JRE 21 :). First in chain.
> Import jre-21

- containers/images/external-secrets/.gitignore
- containers/images/external-secrets/Dockerfile
- containers/images/external-secrets/README.md
- containers/images/external-secrets/conf.sh
- containers/images/external-secrets/init.sh
Adds external secret
Internal task
> Add external-secrets

- .github/workflows/build-manual.yml
Add missing git option to build-manual.yml
> Add git image

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/etcd/Dockerfile
- containers/images/etcd/README.md
- containers/images/etcd/init.sh
- containers/tests/test_etcd.py
> add etcd image

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/elasticsearch/Dockerfile
- containers/images/elasticsearch/README.md
- containers/images/elasticsearch/elasticsearch.yml
- containers/images/elasticsearch/init.sh
- containers/tests/test_elasticsearch.py
#68 
Build and tests passed: https://github.com/SourceMation/images/actions/runs/17826297560
> Add Elasticsearch

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/grafana/.gitignore
- containers/images/grafana/Dockerfile
- containers/images/grafana/README.md
- containers/images/grafana/grafana.ini
- containers/images/grafana/init.sh
- containers/tests/test_grafana.py
Build and tests passed: https://github.com/SourceMation/images/actions/runs/17908290286
> Add grafana image

- containers/images/alertmanager/Dockerfile
- containers/tests/test_alertmanager.py
> fix: set nobody as default user; place binaries in /usr/local/bin/

- containers/images/rabbitmq-4/Dockerfile
- containers/images/rabbitmq-4/README.md
fix erlang version on rabbitmq-4 containers
internal task
> fix: use erlang-27

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/keycloak/.gitignore
- containers/images/keycloak/Dockerfile
- containers/images/keycloak/README.md
- containers/images/keycloak/entrypoint.sh
- containers/images/keycloak/init.sh
- containers/tests/test_keycloak.py
> Rk keycloak

- containers/images/hugo/Dockerfile
- containers/images/hugo/README.md
> no ENTRYPOINT

- containers/images/keycloak-25/README.md
- containers/images/keycloak/README.md
> Fix cmd in README

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/keycloak-config-cli/.gitignore
- containers/images/keycloak-config-cli/Dockerfile
- containers/images/keycloak-config-cli/README.md
- containers/images/keycloak-config-cli/config.json
- containers/images/keycloak-config-cli/entrypoint.sh
- containers/images/keycloak-config-cli/init.sh
- containers/tests/test_keycloak-config-cli.py
#159
Build and tests passed: https://github.com/SourceMation/images/actions/runs/18127409039
> Keycloak config cli

- .github/workflows/build-manual.yml
- containers/build-container.sh
- containers/images/cassandra/.gitignore
- containers/images/cassandra/Dockerfile
- containers/images/cassandra/README.md
- containers/images/cassandra/entrypoint.sh
- containers/images/cassandra/init.sh
- containers/tests/test_cassandra.py
Add Cassandra image
#77 
Build and tests passed: https://github.com/SourceMation/images/actions/runs/18317682566
> Add Cassandra image
